### ISSUE TITLE
RC issues

### ISSUE THREAD

**Issue by sparkblaze** [rokett/Citrix-NetScaler-Exporter#24]
When the exporter fails to query a netscaler, the page should fail, otherwise prometheus will consider it 'up' and scrape no metrics.

the target example does not specify that `http` or `https` is required - it'd be nice if this could be defined either as a url paramater or just assume https - because security.

```
  - job_name: 'netscaler'
    metrics_path: /netscaler
    params:
      ignore-cert: ["yes"]
    static_configs:
      - targets:
          - netscaler-internal.domain.tld
          - netscaler-external.domain.tld
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9280  # The exporter's real host:port running in "multi-query" mode
```
